Import('*')

# Only build TraceCPU if we have support for protobuf as TraceCPU relies on it
SimObject('TraceCPU.py', sim_objects=['TraceCPU'], add_tags='protobuf')
Source('trace_cpu.cc', add_tags='protobuf')

DebugFlag('TraceCPUData')
DebugFlag('TraceCPUInst')
