# -*- mode:python -*-

# Copyright (c) 2006 The Regents of The University of Michigan
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

if not env['CONF']['USE_X86_ISA']:
    Return()

SimObject('Pc.py', sim_objects=['Pc'], add_tags='x86 isa')
Source('pc.cc', add_tags='x86 isa')

SimObject('SouthBridge.py', sim_objects=['SouthBridge'], add_tags='x86 isa')
Source('south_bridge.cc', add_tags='x86 isa')

SimObject('Cmos.py', sim_objects=['Cmos'], add_tags='x86 isa')
Source('cmos.cc', add_tags='x86 isa')
DebugFlag('CMOS', 'Accesses to CMOS devices', add_tags='x86 isa')

SimObject('I8259.py', sim_objects=['I8259'], enums=['X86I8259CascadeMode'],
    add_tags='x86 isa')
Source('i8259.cc', add_tags='x86 isa')
DebugFlag('I8259', 'Accesses to the I8259 PIC devices', add_tags='x86 isa')

SimObject('I8254.py', sim_objects=['I8254'], add_tags='x86 isa')
Source('i8254.cc', add_tags='x86 isa')
DebugFlag('I8254', 'Interrupts from the I8254 timer', add_tags='x86 isa');

SimObject('I8237.py', sim_objects=['I8237'], add_tags='x86 isa')
Source('i8237.cc', add_tags='x86 isa')
DebugFlag('I8237', 'The I8237 dma controller', add_tags='x86 isa');

SimObject('I8042.py', sim_objects=['I8042'], add_tags='x86 isa')
Source('i8042.cc', add_tags='x86 isa')
DebugFlag('I8042', 'The I8042 keyboard controller', add_tags='x86 isa');

SimObject('X86Ide.py', sim_objects=['X86IdeController'], add_tags='x86 isa');
Source('ide_ctrl.cc', add_tags='x86 isa')

SimObject('PcSpeaker.py', sim_objects=['PcSpeaker'], add_tags='x86 isa')
Source('speaker.cc', add_tags='x86 isa')
DebugFlag('PcSpeaker', add_tags='x86 isa')

SimObject('I82094AA.py', sim_objects=['I82094AA'], add_tags='x86 isa')
Source('i82094aa.cc', add_tags='x86 isa')
DebugFlag('I82094AA', add_tags='x86 isa')

SimObject(
    'X86QemuFwCfg.py', sim_objects=['QemuFwCfgItemE820'], add_tags='x86 isa'
)
Source('qemu_fw_cfg.cc', add_tags='x86 isa')
